// ─── Markdown report formatter ────────────────────────────────────────────────
// Converts a completed ResearchState into a polished, self-contained markdown doc.

import type { ResearchState } from "../types.js";

export function toMarkdownReport(state: ResearchState): string {
  const {
    topic,
    subQuestions,
    synthesis,
    citations,
    qualityScore,
    reflectionPassed,
    errors,
  } = state;

  const now = new Date().toISOString();

  const cleanSynthesis = synthesis.replace(/<!--[\s\S]*?-->/g, "").trim();

  const lines: string[] = [
    `# Research Report: ${topic}`,
    ``,
    `> **Generated:** ${now}  `,
    `> **Quality Score:** ${qualityScore ?? "N/A"}/100  `,
    `> **Reflection:** ${reflectionPassed ? "✅ Passed" : "⚠️ Below threshold"}`,
    ``,
    `---`,
    ``,
    `## Research Questions`,
    ``,
    ...subQuestions.map((q, i) => `${i + 1}. ${q}`),
    ``,
    `---`,
    ``,
    cleanSynthesis,
    ``,
  ];

  if (citations.length > 0) {
    lines.push(`---`, ``, `## References`, ``);
    for (const c of citations) {
      lines.push(`**${c.id}** [${c.title}](${c.url})`);
      if (c.excerpt) lines.push(`  > ${c.excerpt}`);
      lines.push(``);
    }
  }

  if (errors && errors.length > 0) {
    lines.push(
      `---`,
      ``,
      `## Pipeline Warnings`,
      ``,
      ...errors.map((e) => `- ⚠️ ${e}`),
      ``,
    );
  }

  lines.push(`---`, ``, `*Generated by @onyx/research — ONYX Sovereign AI OS*`);

  return lines.join("\n");
}