export { onyxCharacter } from "./character";
export { OnyxRuntime, createOnyxRuntime, MEMORY_TABLES, ConversationTelemetry } from "./runtime";
export * from "./actions";
export { walletStateProvider } from "./providers/wallet";
export { budgetRemainingProvider } from "./providers/budget";
export { screenContextProvider } from "./providers/context";
export { memoryStateProvider } from "./providers/memory-state";
export { budgetCheckEvaluator } from "./evaluators/budget";
export { learningExtractorEvaluator } from "./evaluators/learning";
export { nosanaPlugin, buildNosanaJobDef, nosanaStatusProvider, NosanaJobDefinition } from "./plugins/nosana";
export { solanaPlugin, solanaNetworkProvider } from "./plugins/solana";
export { umbraPlugin } from "./plugins/umbra";
export { ikaPlugin } from "./plugins/ika";
export { encryptPlugin } from "./plugins/encrypt";
export { claudeMemPlugin, restoreMemoriesAction, persistMemoriesEvaluator } from "./plugins/claude-mem";
export { deepTutorPlugin, checkProgressAction, learnerProfileProvider } from "./plugins/deep-tutor";
export { last30DaysPlugin, recentIntelProvider } from "./plugins/last30days";

export const NAME = "onyx-agent";
export const VERSION = "0.1.0";